// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createTodoStmt, err = db.PrepareContext(ctx, createTodo); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTodo: %w", err)
	}
	if q.deleteTodoByIdStmt, err = db.PrepareContext(ctx, deleteTodoById); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTodoById: %w", err)
	}
	if q.getAllTodosStmt, err = db.PrepareContext(ctx, getAllTodos); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllTodos: %w", err)
	}
	if q.getTodoByIdStmt, err = db.PrepareContext(ctx, getTodoById); err != nil {
		return nil, fmt.Errorf("error preparing query GetTodoById: %w", err)
	}
	if q.updateTodoStmt, err = db.PrepareContext(ctx, updateTodo); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTodo: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createTodoStmt != nil {
		if cerr := q.createTodoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTodoStmt: %w", cerr)
		}
	}
	if q.deleteTodoByIdStmt != nil {
		if cerr := q.deleteTodoByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTodoByIdStmt: %w", cerr)
		}
	}
	if q.getAllTodosStmt != nil {
		if cerr := q.getAllTodosStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllTodosStmt: %w", cerr)
		}
	}
	if q.getTodoByIdStmt != nil {
		if cerr := q.getTodoByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTodoByIdStmt: %w", cerr)
		}
	}
	if q.updateTodoStmt != nil {
		if cerr := q.updateTodoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTodoStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                 DBTX
	tx                 *sql.Tx
	createTodoStmt     *sql.Stmt
	deleteTodoByIdStmt *sql.Stmt
	getAllTodosStmt    *sql.Stmt
	getTodoByIdStmt    *sql.Stmt
	updateTodoStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                 tx,
		tx:                 tx,
		createTodoStmt:     q.createTodoStmt,
		deleteTodoByIdStmt: q.deleteTodoByIdStmt,
		getAllTodosStmt:    q.getAllTodosStmt,
		getTodoByIdStmt:    q.getTodoByIdStmt,
		updateTodoStmt:     q.updateTodoStmt,
	}
}
